name: Compile Article PDF

on:
  push:
    branches:
      - 'main'
    paths:
      - 'report/**'
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./report/src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra texlive-publishers biber
      - name: Install Python dependencies on Ubuntu
        run: sudo apt-get install -y python3-pygments
      - name: Install Pygments
        run: |
          pip install --upgrade Pygments
          pip show pygments

      # Runs latex script
      - name: Compile LaTeX
        run: |
          latexmk main.tex -pdf -shell-escape -synctex=1 -interaction=nonstopmode -f
          biber main
          latexmk main.tex -pdf -shell-escape -synctex=1 -interaction=nonstopmode -f
          latexmk main.tex -pdf -shell-escape -synctex=1 -interaction=nonstopmode -f
          dir

      # Save pdf as artifact
      - name: Save artifact with build results
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./report/src/main.pdf
          retention-days: 7

  push:
    needs: [pdf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download pdf artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./report/src/main.pdf
      - name: Push to repo
        run: |
          git config user.name Maltesius
          git config user.email andersmalta@gmail.com
          git add /home/runner/work/P9-ZKP/P9-ZKP/report/src/main.pdf
          git commit -m "Added by GitHub Action"
          git remote set-url --push origin https://your_username:$GITHUB_TOKEN@github.com/AAU-Dat/P9-ZKP
          git push
